topicos <- c("I - ATIVIDADES DE ENSINO",
             "I-1 Ensino Básico",
             "I-1 Graduação",
             "I-2 Pós-Graduação Stricto Sensu",
             "I-2 Pós-Graduação Latu Sensu",
             "I-3 Projetos de Ensino",
             "II - PRODUÇÃO INTELECTUAL",
             "II-1 Produção Científica",
             "II-2 Produção Artística e Cultural",
             "II-3 Produção Técnica ou Tecnológica",
             "II-4 Outro Tipo de Produção",
             "III - ATIVIDADES DE PESQUISA E DE EXTENSÃO",
             "II-1 Produção Científica",
             "II-2 Produção Artística e Cultural",
             "II-3 Produção Técnica ou Tecnológica",
             "II-4 Outro Tipo de Produção",
             "III - ATIVIDADES DE PESQUISA E DE EXTENSÃO",
             "III-1 Atividades de Pesquisa",
             "III-2 Atividades de Extensão",
             "IV - ATIVIDADES ADMINISTRATIVAS E DE REPRESENTAÇÃO",
             "IV-1 Direção e Função Gratificada",
             "IV–2 Atividades Administrativas",
             "IV-3 Outras Atividades Administrativas",
             'IV-4 Atividades de Representação Fora da UFG',
             'V - OUTRAS ATIVIDADES',
             "V-1 Atividades Acadêmicas - Orientação",
             "V-2 Atividades Acadêmicas - Bancas e Cursos",
             "V-3 Atividades de Aprendizado e Aperfeiçoamento")

save(topicos, file = 'data/topicos.rda')

