---
title: "Instalação do R, RStudio, e Pacote radocr"
author: "Seu Nome"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Instalação do R, RStudio, e Pacote radocr}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introdução

Esta vinheta fornece um guia passo a passo para a instalação do R, RStudio, e do pacote `radocr`.

## Instalação do R

Para instalar o R, siga os passos abaixo de acordo com o seu sistema operacional:

### Windows

1. Acesse o site do [CRAN](https://cran.r-project.org/).
2. Clique em "Download R for Windows".
3. Clique em "base" e, em seguida, em "Download R 4.x.x for Windows" (onde x.x corresponde à versão mais recente).
4. Siga as instruções do instalador.

### Mac OS

1. Acesse o site do [CRAN](https://cran.r-project.org/).
2. Clique em "Download R for macOS".
3. Baixe a versão mais recente do R.
4. Siga as instruções do instalador.

### Linux

No Linux, você pode instalar o R diretamente do repositório de pacotes da sua distribuição. Por exemplo, no Ubuntu, use os comandos:

```bash
sudo apt update
sudo apt install r-base
```
## Instalação do RStudio

RStudio é uma IDE para R que facilita a escrita e execução de código. Para instalar o RStudio:

1. Acesse o site do [RStudio](https://www.rstudio.com/products/rstudio/download/).
2. Baixe a versão apropriada para o seu sistema operacional.
3. Siga as instruções do instalador.

# radocr

O pacote `radocr` fornece ferramentas para processar arquivos PDF contendo os
RADOCs dos docentes e gerar arquivos formatados (em LaTeX ou e Excel).

## Instalação do Pacote `radocr`

Para instalar o pacote `radocr` a partir do GitHub, você precisa primeiro instalar o pacote `devtools`, que permite a instalação de pacotes diretamente do GitHub. Abra o RStudio e execute os comandos abaixo:

```r
# Instale o pacote devtools, se ainda não tiver instalado
install.packages("devtools")
```
# Carregue o devtools
```r
library(devtools)
```
# Instale o pacote radocr a partir do GitHub
```r
install_github("maxlemes/radocr")
```

## Carregamento do Pacote
Após a instalação, carregue o pacote com:

```r
library(radocr)
```

## Funções Principais

###  `resumo_tex` e `resumo_xlsx`

As funções `resumo_tex` e `resumo_xlsx` criam um arquivo com o resumo das
atividades do docente contidas nos dois RADOCs inserido (em PDF). A diferença entre
elas é que enquanto a função `resumo_tex` gera um arquivo LaTeX (.tex) a função
`resumo_xlsx` gera uma planilha em Excel (.xlsx).

#### Descrição

A função lê os dados dos RADOCs em dois arquivos PDF e retorna um arquivo com as
atividades contidas nos arquivos.

#### Parâmetros

- **`pdf_file1`**: Caminho para o primeiro arquivo PDF contendo o RADOC.
- **`pdf_file2`**: Caminho para o segundo arquivo PDF contendo o RADOC.
- **`output_file`**: Caminho onde o arquivo LaTeX será salvo. Se não fornecido, o arquivo será salvo na pasta atual.

#### Detalhes

- Se o parâmetro `output_file` não for especificado, o arquivo `.tex` será salvo no diretório atual de trabalho.

#### Exemplos

**Exemplo 1:**

```r
pdf_radoc1 <- "pasta_do_arquivo/radoc1.pdf"
pdf_radoc2 <- "pasta_do_arquivo/radoc2.pdf"
output_file <- "pasta_de_destino/nome_arquivo.tex"
resumo_tex(pdf_radoc1, pdf_radoc2, output_file)
```

**Exemplo 2:**

```r
pdf_radoc1 <- "pasta_do_arquivo/radoc1.pdf"
pdf_radoc2 <- "pasta_do_arquivo/radoc2.pdf"
output_file <- "pasta_de_destino/nome_arquivo.xlsx"
resumo_xlsx(pdf_radoc1, pdf_radoc2, output_file)
```

###  `tabela_cad_tex` e `tabela_cad_xlsx`

As funções `tabela_cad_tex` e `tabela_cad_xlsx` criam um arquivo com a Tabela
Cad a partir de dois arquivos PDF contendo RADOCs. A diferença entre elas é que
enquanto a função `tabela_cad_tex` gera um arquivo LaTeX (.tex) a função
`tabela_cad_xlsx` gera uma planilha em Excel (.xlsx).

#### Descrição

A função lê os dados dos RADOCs em dois arquivos PDF e retorna um arquivo com a Tabela Cad preenchida.

#### Parâmetros

- **`pdf_file1`**: Caminho para o primeiro arquivo PDF contendo o RADOC.
- **`pdf_file2`**: Caminho para o segundo arquivo PDF contendo o RADOC.
- **`output_file`**: Caminho onde o arquivo LaTeX será salvo. Se não fornecido, o arquivo será salvo na pasta atual.

#### Detalhes

- Se o parâmetro `output_file` não for especificado, o arquivo `.tex` será salvo no diretório atual de trabalho.

#### Exemplos

**Exemplo 1:**

```r
pdf_radoc1 <- "pasta_do_arquivo/radoc1.pdf"
pdf_radoc2 <- "pasta_do_arquivo/radoc2.pdf"
output_file <- "pasta_de_destino/nome_arquivo.tex"
tabela_cad_tex(pdf_radoc1, pdf_radoc2, output_file)
```

**Exemplo 2:**

```r
pdf_radoc1 <- "pasta_do_arquivo/radoc1.pdf"
pdf_radoc2 <- "pasta_do_arquivo/radoc2.pdf"
output_file <- "pasta_de_destino/nome_arquivo.xlsx"
tabela_cad_xlsx(pdf_radoc1, pdf_radoc2, output_file)
```
