#' Função que faz 3 testes nos arquivos
#'
#' 1) Testa se o arquivo é um RADOC do SICAD+
#' 2) Testa se os dois RADOCs são do memso docente
#' 3) Testa se os dois RADOCs são de anos distintos
#'
#' @param pdf_file1,pdf_file2 dois arquivos em pdf
#'
#' @return Uma mensagem com a avaliação feita
#'
#' @examples
#'\dontrun{
#' filesCheck(pdf_file1, pdf_file2)
#' }
filesCheck <- function(pdf_file1, pdf_file2){

  files <- c(pdf_file1, pdf_file2)

  aux <- NULL
  ano <- NULL

  # Teste para verificar se os arquivos são RADOCs do SICAD+
  for (i in 1:length(files)) {

    tabela <- readr::read_lines(pdftools::pdf_text(files[i]))
    tabela <- stringr::str_replace_all(tabela, "^\\s+|\\s+$", "")

    if (!grepl('^Sistema de Consulta das Atividades Docente', tabela[1])){
      stop(paste('The file', files[i],
                 'does not appear to be a RADOC generated by SICAD+.'))
    }

    # Teste para verificar se os dois RADOCs são do mesmo docente
    aux[i] <- stringr::str_extract(
      tabela[xts::first(which(stringr::str_detect(tabela, "^SIAPE:")))],
      '(^.*[A-Z]?[^\\s](?=\\s\\s))')

    if (i > 1){
      if (aux[i] != aux[i-1]){
        stop('The RADOCs are not from the same teacher.')
      }
    }

    # Teste para verificar se os dois RADOCs são do mesmo ano
    ind_ano <- tabela[xts::first(
      which(stringr::str_detect(tabela, "^Relat\\u00f3rio do docente")))]
    ano[i] <- as.numeric(stringr::str_sub(
      stringr::str_extract(ind_ano,
                           "(?<=\\()([^()]*?)(?=\\)[^()]*$)"),start = 5))

     if (i > 1){
      if (ano[i] == ano[i-1]){
        stop('The RADOCs are from the same year.')
      }
     }
  }

  return('Success: files checked.')
}
